import type { SVGProps } from "react";

const SvgIconSpinner = (props: SVGProps<SVGSVGElement>) => (
  <svg
    xmlns='http://www.w3.org/2000/svg'
    data-testid='icon-spinner'
    viewBox='0 0 24 24'
    {...props}
  >
    <circle cx={4} cy={12} r={0} fill='currentColor'>
      <animate
        fill='freeze'
        attributeName='r'
        begin='icon-spinner_svg__0;a.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='0;3'
      />
      <animate
        fill='freeze'
        attributeName='cx'
        begin='icon-spinner_svg__b.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='4;12'
      />
      <animate
        fill='freeze'
        attributeName='cx'
        begin='icon-spinner_svg__c.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='12;20'
      />
      <animate
        id='icon-spinner_svg__e'
        fill='freeze'
        attributeName='r'
        begin='icon-spinner_svg__d.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='3;0'
      />
      <animate
        id='icon-spinner_svg__a'
        fill='freeze'
        attributeName='cx'
        begin='icon-spinner_svg__e.end'
        dur='0.001s'
        values='20;4'
      />
    </circle>
    <circle cx={4} cy={12} r={3} fill='currentColor'>
      <animate
        fill='freeze'
        attributeName='cx'
        begin='icon-spinner_svg__0;a.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='4;12'
      />
      <animate
        fill='freeze'
        attributeName='cx'
        begin='icon-spinner_svg__b.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='12;20'
      />
      <animate
        id='icon-spinner_svg__f'
        fill='freeze'
        attributeName='r'
        begin='icon-spinner_svg__c.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='3;0'
      />
      <animate
        id='icon-spinner_svg__d'
        fill='freeze'
        attributeName='cx'
        begin='icon-spinner_svg__f.end'
        dur='0.001s'
        values='20;4'
      />
      <animate
        fill='freeze'
        attributeName='r'
        begin='icon-spinner_svg__d.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='0;3'
      />
    </circle>
    <circle cx={12} cy={12} r={3} fill='currentColor'>
      <animate
        fill='freeze'
        attributeName='cx'
        begin='icon-spinner_svg__0;a.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='12;20'
      />
      <animate
        id='icon-spinner_svg__g'
        fill='freeze'
        attributeName='r'
        begin='icon-spinner_svg__b.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='3;0'
      />
      <animate
        id='icon-spinner_svg__c'
        fill='freeze'
        attributeName='cx'
        begin='icon-spinner_svg__g.end'
        dur='0.001s'
        values='20;4'
      />
      <animate
        fill='freeze'
        attributeName='r'
        begin='icon-spinner_svg__c.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='0;3'
      />
      <animate
        fill='freeze'
        attributeName='cx'
        begin='icon-spinner_svg__d.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='4;12'
      />
    </circle>
    <circle cx={20} cy={12} r={3} fill='currentColor'>
      <animate
        id='icon-spinner_svg__h'
        fill='freeze'
        attributeName='r'
        begin='icon-spinner_svg__0;a.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='3;0'
      />
      <animate
        id='icon-spinner_svg__b'
        fill='freeze'
        attributeName='cx'
        begin='icon-spinner_svg__h.end'
        dur='0.001s'
        values='20;4'
      />
      <animate
        fill='freeze'
        attributeName='r'
        begin='icon-spinner_svg__b.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='0;3'
      />
      <animate
        fill='freeze'
        attributeName='cx'
        begin='icon-spinner_svg__c.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='4;12'
      />
      <animate
        fill='freeze'
        attributeName='cx'
        begin='icon-spinner_svg__d.end'
        calcMode='spline'
        dur='0.5s'
        keySplines='.36,.6,.31,1'
        values='12;20'
      />
    </circle>
  </svg>
);
export default SvgIconSpinner;
